#!/bin/sh

set -e

# search 32-bits libs too
LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$SNAP/lib/i386-linux-gnu"
LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$SNAP/usr/lib/i386-linux-gnu"

# locales are missing and break startup
export LC_ALL=C

# ran generates config and writes logs and slots in current directory by default
cd "$SNAP_DATA"

exec "$SNAP/ran" "$@"
