#!/bin/sh

set -e

# search 32-bits libs too
LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$SNAP/lib/i386-linux-gnu"
LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$SNAP/usr/lib/i386-linux-gnu"

# locales are missing and break startup
export LC_ALL=C

# enable IP forwarding
sysctl net.ipv4.ip_forward=1

#set ulimit for core dump 

ulimit -c unlimited

# ran generates config and writes logs and slots in current directory by default
cd "$SNAP_DATA"
#cd "$SNAP"
# Copy the ecx.db and hlr.db for the first intall to SNAP directory.
ecx_db="$SNAP_DATA/ecx.db"

if [ ! -f "$ecx_db" ]; then
	cp "$SNAP/ecx.db" $ecx_db
fi

hlr_db="$SNAP_DATA/hlr.db"

if [ ! -f "$hlr_db" ]; then
	cp "$SNAP/hlr.db" $hlr_db
fi

exec "$SNAP/ran" "$@"
