name: quortus-epc-lool
version: 3.97.1
summary: Quortus ECX core network for cellular network
description: |
  Quortus ECX Core is a fully-featured virtualized core for cellular networks.
  It supports 4G LTE, 3G and GSM radio networks with VoLTE / SIP voice, packet
  data and SMS, either in a standalone deployment or with operator interconnect.
  ECX Core is designed for scalability.
grade: devel
confinement: devmode

apps:
  check-sys:
    command: check-sys
  ran:
    command: ran-launcher
    daemon: simple
  rancli:
    command: rancli-launcher

parts:
  # debs part require installation of i386 packages
  i386-arch:
    plugin: nil
    build: |
      set -e
      if ! dpkg --print-foreign-architectures | grep -qxF i386; then
          sudo dpkg --add-architecture i386
          sudo apt update
      fi

  # 32-bits C/C++ libraries
  debs:
    after: [ i386-arch, ]
    plugin: nil
    stage-packages: ["libstdc++6:i386", ]

  # Quortus ECX prebuilt binaries
  ran:
    plugin: dump
    source: ran_V3_97_1.gz
    source-type: tar
    # don't copy missing shared libs
    build-attributes: [ no-system-libraries, ]
    install: |
      ln -sf ran $SNAPCRAFT_PART_INSTALL/rancli
    stage:
      - ran
      - rancli
      - lib/*.so*

  glue:
    plugin: dump
    source: glue

