name: quortus-epc
version: 3.97.400
summary: Quortus ECX core network for cellular network
description: |
  Quortus ECX Core is a fully-featured virtualized core for cellular networks.
  It supports 4G LTE, 3G and GSM radio networks with VoLTE / SIP voice, packet
  data and SMS, either in a standalone deployment or with operator interconnect.
  ECX Core is designed for scalability.
#grade: devel
grade: stable
#confinement: devmode
confinement: strict

apps:
  core:
    command: core-launcher
  check-sys:
    command: check-sys
    plugs: [firewall-control]
  ran:
    command: ran-launcher
    daemon: simple
    plugs: [network,network-control,firewall-control]
  rancli:
    command: rancli-launcher
    plugs: [network]
  lighttpd:
    command: lighttpd-launcher
    daemon: simple
    plugs: [network-bind]

parts:
  # debs part require installation of i386 packages
  i386-arch:
    plugin: nil
    build: |
      set -e
      if ! dpkg --print-foreign-architectures | grep -qxF i386; then
          sudo dpkg --add-architecture i386
          sudo apt update
      fi

  # 32-bits C/C++ libraries
  debs:
    after: [ i386-arch, ]
    plugin: nil
    stage-packages: ["libstdc++6:i386", ]

  # Quortus ECX prebuilt binaries
  ran: 
    plugin: dump
    source: ran_PocketEPC_HAW40.gz
    source-type: tar
    # don't copy missing shared libs
    build-attributes: [ no-system-libraries, ]
    install: |
      # rancli -> ran symlink
      ln -sf ran $SNAPCRAFT_PART_INSTALL/rancli
      # unpack lighttpd binaries into snap
      tar -C $SNAPCRAFT_PART_INSTALL -xf lighttpd.tar.gz
      # unpack www files into snap
      mkdir $SNAPCRAFT_PART_INSTALL/www
      tar -C $SNAPCRAFT_PART_INSTALL/www -xf soapWebscreensx86.tar
      # replace dirs with symlinks to rw space
      rm -rf $SNAPCRAFT_PART_INSTALL/www/fingerprinted
      ln -snf /var/snap/quortus-epc/current/fingerprinted $SNAPCRAFT_PART_INSTALL/www/fingerprinted
      rm -rf $SNAPCRAFT_PART_INSTALL/settings
      ln -snf /var/snap/quortus-epc/current/settings $SNAPCRAFT_PART_INSTALL/settings
    stage:
      - ran
      - ecx.db
      - hlr.db
      - rancli
      - lib/*.so*
      - lighttpd
      - settings
      - www

  glue:
    plugin: dump
    source: glue

